export const actionMap = {
  "GET /api/rooms/most-booking-room": "User view the most frequently booked rooms",
  "GET /api/rooms/get-each-room-type": "User view each room type",
  "GET /api/users/profile": "View Profile",
  "GET /api/bookings/get-booking-session/:uuid": "Get booking session",
  "PATCH /api/bookings/update-breakfast-count/:objectId": "Add breakfast for the room",
  "POST /api/bookings/get-booking-session/:uuid": "Make payment",
  "DELETE /api/bookings/delete-booking-session/:uuid": "Cancelled Booking",
  "GET /api/bookings/get-booking-session-by-user": "Load pending booking",
  "GET /api/bookings/get-user-booking": "fetching current user booking history",
  "POST /api/bookings/cancel-booking": "Request to cancelled booking",
  "POST /api/bookings/create-booking": "Create Booking",
  "POST /create-booking-session/:uuid": "Start booking session",
  "POST /api/reward/rewards": "Admin Created Rewards",
  "GET /api/reward/rewards": "Admin Get All Rewards",
  "POST /api/reward/reward-claim/:objectId": "User claimed reward",
  "GET /api/reward/show-user-claimed-reward": "Load User claimed reward",
  "POST /api/reward/reward-code-used": "Users used reward code",
  "POST /api/reward/remove-reward-code": "Users remove current use reward code",
  "GET /api/checkout/payment-gateway": "Payment has been cancelled by the user",
  "POST /api/checkout/payment-gateway": "User successfully pay",
  "GET /api/rooms/filter": "User filtering room type",
  "POST /api/users/login": "User are trying to login",
  "POST /api/users/verify-otp": "Admin trying to accessing admin features",
  "PUT /api/users/updateProfile/:objectId": "Users changing their profile",
  "POST /api/event/event-enquiry": "Users are trying to request of host an event in hotel",
  "POST /api/admin/add-room": "Admin add a new room",
  "PATCH /api/admin/update-room-status/:objectId": "Admin updated room status",
  "PUT /api/admin/update-room/:objectId": "Admin edit current existing room",
  "PUT /api/admin/update-event-statu/:objectId": "Admin accepted event request",
  "DELETE /api/admin/delete-event-status/:objectId": "Admin decline event request",
  "POST /api/facilities/create-facility": "Admin add new facility",
  "PATCH /api/facilities/update-facility-status/:objectId": "Admin update facility status",
  "DELETE /api/facilities/delete-facility/:objectId": "Admin deleted current existing facility",
  "PUT /api/facilities/update-facility/:objectId": "Admin edit current existing facility",
  "GET /api/facilities/facility/:objectId": "Users entering each facility",
  "DELETE /api/admin/delete-room/683c9c7c018c0d9c29094e57": "Admin has deleted a current existing room",
  "POST /api/systemSetting/report": "Admin generate a new report",
  "GET /api/systemSetting/report": "Admin view a current existing report",
  "GET /api/systemSetting/download-report/:objectId/": "Admin download an existing report",
  "DELETE /api/systemSetting/report": "Super Admin Deleted current existing report",
  "GET /api/invoices/invoice/:objectId": "User checking their own invoice",
  "POST /api/users/logout": "User has been logout",
  "PATCH /api/admin/update-pending-status-to-confirm": "Admin updated all pending booking status to confirmed" //update all pending booking status to confirmed
};
